---
title: "Kidney Cancer Exercise"
output: html_document
---

**From:** “Beyond Calculations: Teaching Statistical Thinking”

E. Ashley Steel asteel@fs.fed.us

**Overview**

In this activity the students brainstorm three possible explanations for a pattern in kidney cancer rates in the USA. Unknowingly, different groups of students are trying to explain opposite patterns. Both patterns are true; they are created by random chance as a result of differences in sample size. 

**Big Ideas**

-  Students discover their own propensity to make up stories that explain patterns.
-  Students observe strong patterns that are caused by random chance.
-  Students are introduced to null models as a tool for identifying patterns caused by random chance.
-  Students gain deep intuition that extreme events are more likely with smaller sample sizes.
-  Students observe a range of examples in which costly errors have been made by not recognizing that extreme events are more likely with smaller sample sizes.

**Set-Up**

Assign students to groups. Groups are most successful if they include a range of backgrounds and R programming skills.

Print discussion sheets and prepare them so that you can pass out one sheet to each group and about half of the groups get one sheet (“kidney cancer rates are highest”) and half of the groups will get the other sheet (“kidney cancer rates are lowest”) without students being aware of the difference between sheets.

Prepare objects to be sampled. One non-transparent bag per group with 80 similar objects, 40 of one color and 40 of another. Effective simulations require that students can’t determine differences in the objects by feel so the objects all need to be about the same shape and size. Marbles, beads, black and white beans of the same shape and size, or squares of colored paper all work. Different types of seashells, big blue marbles and little red marbles, or two kinds of coins would not work.

**Activity**

1)  Have the students sit in their pre-assigned groups.
2)  This activity works best if initiated toward the end of a class period. It works particularly well if students have already learned about how the human brain is programmed to make particular types
of errors.
3)  Pass out the attached handout (2 sheets), giving only 1 sheet to each group and making sure that
about half the groups receive a sheet that says kidney cancer rates are highest in rural counties and
the other half of the groups get a sheet that says kidney cancer rates are lowest in rural counties. Students should not be aware that sheets are different.
4)  Allow 5-10 minutes for discussion within the groups.
5)  Initiate a class discussion with “let’s make a list of the likely explanations for these findings” and start to write student responses on the board. You may need to ask students to explain what they mean when they say “uneven access to health care” as you are looking for more specific responses such as “health care systems are better in urban areas.” Once you start listing answers on the board, the list will be a bit confused and confusing. Some student groups will be saying “these patterns result because hospitals are larger” and other student groups will be saying “these patterns result because hospitals are smaller.” Allow the confusion and end the class without explaining.
6)  For homework, students read: Wainer, H., 2007. The most dangerous equation. American Scientist, 95(3), p.249. [This article explains the kidney cancer example and is a good test as to whether students are completing the reading] Tu, Y.K. and Gilthorpe, M.S., 2007. The most dangerous hospital or the most dangerous equation?. BMC health services research, 7(1), p.185.
http://www.gatesfoundation.org/Media-Center/Press-Releases/2003/04/Oregon-Small-Schools-Initiative
https://www.washingtonpost.com/news/answer-sheet/wp/2014/06/09/how-much-bill-gatess-disappointing-small-schools-effort-really-cost/
7)  When students return to class, have a short discussion on what happened in the kidney cancer exercise. Direct the discussion so that students become aware of the following issues:  They (and all people) naturally create a story to explain observed patterns. This is a tendency of the human brain that one needs to be aware of as a scientist and statistician.  Extreme events are not equally likely across samples of different sizes. Sample size matters in many ways!


**HANDOUTS**

Copy one sheet of the handout per group. Note that the two pages are different, one says that the kidney cancer rates are highest in rural counties and the other says that kidney cancer rates are lowest in rural counties. Prepare the handouts so that you can pass one sheet to each group without the students being aware that all sheets are not identical.

# Handout 1

### Kidney cancer across America

Looking at kidney cancer rates across the over 3,000 counties of the United States
reveals a remarkable pattern. The counties in which kidney cancer rates are
lowest are mostly rural, sparsely populated, and located in traditionally
Republican states in the Midwest, South and West.

Think about these findings and identify three likely explanations.

County: In the United States, a county is a political and geographic subdivision of a state. Of the 50 U.S. states, 48
states are divided into a total of 3,007 counties.
Republican: conservative, nationalist, lower taxes, agriculture, business

# Handout 2

### Kidney cancer across America

Looking at kidney cancer across the over 3,000 counties of the United States
reveals a remarkable pattern. The counties in which kidney cancer rates are
highest are mostly rural, sparsely populated, and located in traditionally
Republican states in the Midwest, South and West.

Think about these findings and identify three likely explanations.

County: In the United States, a county is a political and geographic subdivision of a state. Of the 50 U.S. states, 48
states are divided into a total of 3,007 counties.
Republican: conservative, nationalist, lower taxes, agriculture, business